##############################################
# DESCRIPTION 
# Convert .prmtop and .inpcrd files generated by tleap to
# .top and .gro files required to run GROMACS
#
##############################################

import parmed as pmd
import glob
from parmed.tools import netCharge
from mdfptools.Extractor import *

import argparse

parser = argparse.ArgumentParser(description='Convert .prmtop and .inpcrd files generated by tleap to .top and .gro files required to run GROMACS')
#parser.add_argument('-isdf', metavar='input_file.sdf', help='input SDF file', required = True)
args = parser.parse_args()

coord_files = glob.glob("*inpcrd")

for coord in coord_files:
    mol_name = coord.split(".")[0]
    amber = pmd.load_file('{}.prmtop'.format(mol_name),coord)
    try:
        amber.save('{}.gro'.format(mol_name))
    except: 
        print ("{}.gro already exists. No overwrite".format(mol_name))
    try:
         amber.save('{}.top'.format(mol_name))
    except: 
        print ("{}.top already exists. No overwrite".format(mol_name))




